#spring.datasource.url=jdbc:mysql://localhost:3306/viajes_db
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.username=root
#spring.datasource.password=Jirafita2020

spring.datasource.url=jdbc:mysql://localhost:3306/viajes_db
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=mati
spring.datasource.password=mati123